image: php:7.2-fpm

pipelines: 
  pull-requests:
    '**': # this runs as default for any branch not elsewhere defined
       - step: 
          name: Run test after each PR
          caches:
              - composer
          artifacts:
            - storage/**
            - vendor/**
            - public/**
            - .env
          script:
            #Update Image
            - apt-get update

            #Install Zip
            - apt-get install -qy zlib1g-dev zip unzip
            - docker-php-ext-install zip

            #Install Git
            - apt-get install -qy git
            - apt-get install -qy curl

            #Install MySql
            - apt-get install -qy mariadb-client
            - docker-php-ext-install pdo_mysql

            #Install Crypt
            - apt-get install -qy libmcrypt-dev
            - yes | pecl install mcrypt-1.0.1

            #Install Composer Platform Reqs
            - docker-php-ext-install bcmath

            #Copy Environment File
            - ln -f -s .env.pipelines .env

            #Install Composer
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            #Migrate Database
            - php artisan key:generate
            - php artisan migrate

            #Run Test Suite
            #- ./vendor/bin/phpunit --verbose
          services:
            #Add MySql Database
            - mysql 
  branches:
    staging:
      - step:
          image: python:3.5.1
          deployment: staging
          script:
            - apt-get update # required to install zip
            - apt-get install -y zip # required for packaging up the application
            - pip install boto3==1.3.0 # required for codedeploy_deploy.py
            - zip -r /tmp/artifact.zip * # package up the application for deployment
            - python codedeploy_deploy.py # run the deployment script
    master:
      - step:
          image: python:3.5.1
          deployment: master
          script:
            - apt-get update # required to install zip
            - apt-get install -y zip # required for packaging up the application
            - pip install boto3==1.3.0 # required for codedeploy_deploy.py
            - zip -r /tmp/artifact.zip * # package up the application for deployment
            - python codedeploy_deploy.py # run the deployment script
definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_DATABASE: 'bitbucket'
        MYSQL_PASSWORD: 'bitbucket'
        MYSQL_USER: 'bitbucket'